/**
 * Generates a professional PDF from section data using the browser's print functionality.
 * Opens a new window with formatted HTML content and triggers print-to-PDF.
 */

interface PdfField {
  label: string;
  value: string | number | boolean | null | undefined;
}

interface PdfSection {
  title: string;
  fields: PdfField[];
  subsections?: { title: string; fields: PdfField[] }[];
}

const fmtValue = (v: PdfField['value']): string => {
  if (v === null || v === undefined || v === '') return '—';
  if (typeof v === 'boolean') return v ? 'Yes' : 'No';
  if (typeof v === 'number') return v.toLocaleString('en-IN');
  return String(v);
};

export function downloadSectionPdf(sections: PdfSection[], studentName: string, applicationId?: string) {
  const win = window.open('', '_blank', 'width=800,height=900');
  if (!win) {
    alert('Please allow pop-ups to download the PDF.');
    return;
  }

  const sectionHtml = sections.map(section => {
    const fieldsHtml = section.fields.map(f => `
      <div class="field">
        <div class="label">${f.label}</div>
        <div class="value">${fmtValue(f.value)}</div>
      </div>
    `).join('');

    const subsectionsHtml = (section.subsections ?? []).map(sub => {
      const subFieldsHtml = sub.fields.map(f => `
        <div class="field">
          <div class="label">${f.label}</div>
          <div class="value">${fmtValue(f.value)}</div>
        </div>
      `).join('');
      return `<div class="subsection"><h3>${sub.title}</h3><div class="grid">${subFieldsHtml}</div></div>`;
    }).join('');

    return `
      <div class="section">
        <h2>${section.title}</h2>
        <div class="grid">${fieldsHtml}</div>
        ${subsectionsHtml}
      </div>
    `;
  }).join('');

  win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>GradCredit — ${studentName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Manrope', 'Inter', -apple-system, sans-serif;
      color: #1a1a1a;
      padding: 40px;
      background: #fff;
    }
    .header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #222222;
    }
    .logo {
      width: 40px; height: 40px;
      background: linear-gradient(135deg, #222222, #444444);
      border-radius: 10px;
      display: flex; align-items: center; justify-content: center;
      font-size: 20px; font-weight: 800; color: #FAFAFA;
    }
    .header-text h1 { font-size: 18px; font-weight: 700; }
    .header-text p { font-size: 11px; color: #666; margin-top: 2px; }
    .meta {
      display: flex; justify-content: space-between;
      font-size: 11px; color: #666;
      margin-bottom: 24px;
    }
    .section {
      margin-bottom: 28px;
      page-break-inside: avoid;
    }
    .section h2 {
      font-size: 14px; font-weight: 700;
      color: #1F1F22;
      margin-bottom: 12px;
      padding-bottom: 6px;
      border-bottom: 1px solid #e0e0e0;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .subsection {
      margin-top: 16px;
    }
    .subsection h3 {
      font-size: 12px; font-weight: 600;
      color: #333;
      margin-bottom: 8px;
    }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 10px 24px;
    }
    .field {
      padding: 6px 0;
    }
    .field .label {
      font-size: 10px;
      color: #888;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.3px;
      margin-bottom: 2px;
    }
    .field .value {
      font-size: 13px;
      color: #1a1a1a;
      font-weight: 500;
    }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e0e0e0;
      font-size: 10px;
      color: #999;
      text-align: center;
    }
    @media print {
      body { padding: 20px; }
      .section { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">G</div>
    <div class="header-text">
      <h1>GradCredit</h1>
      <p>Bridging Borders. Fueling Futures.</p>
    </div>
  </div>
  <div class="meta">
    <span>Student: <strong>${studentName}</strong></span>
    <span>Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</span>
    ${applicationId ? `<span>Application ID: ${applicationId.slice(0, 8)}</span>` : ''}
  </div>
  ${sectionHtml}
  <div class="footer">
    This document was generated by GradCredit. For verification, please contact info@gradcredit.com or call +91 9564159999.
  </div>
  <script>
    window.onload = () => { setTimeout(() => window.print(), 300); };
  </script>
</body>
</html>`);
  win.document.close();
}
